global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "object_detection"
    static_configs:
      # Use environment variable for target, default to localhost:8000
      # Set METRICS_ENDPOINT=host.docker.internal:8000 when running docker on mac/windows
      # Or set to the appropriate service name/IP if using docker-compose/k8s
      - targets: ["${METRICS_ENDPOINT:-localhost:8000}"]
